/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MiPrimerContrato } from "./MiPrimerContrato";
export * as factories from "./factories";
export { MiPrimerContrato__factory } from "./factories/MiPrimerContrato__factory";
