/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MiPrimerContratoInterface extends Interface {
  getFunction(
    nameOrSignature: "actualizarMensaje" | "mensaje"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "actualizarMensaje",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "mensaje", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "actualizarMensaje",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mensaje", data: BytesLike): Result;
}

export interface MiPrimerContrato extends BaseContract {
  connect(runner?: ContractRunner | null): MiPrimerContrato;
  waitForDeployment(): Promise<this>;

  interface: MiPrimerContratoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  actualizarMensaje: TypedContractMethod<
    [_nuevoMensaje: string],
    [void],
    "nonpayable"
  >;

  mensaje: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "actualizarMensaje"
  ): TypedContractMethod<[_nuevoMensaje: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mensaje"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
